# Generated by Django 4.1.2 on 2022-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_remove_instructor_email_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='specialty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
