# Generated by Django 4.1.2 on 2022-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructor_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorskill',
            name='detail',
        ),
        migrations.AddField(
            model_name='instructorcontactinfo',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorskill',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='instructorsocialmedia',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
