# Generated by Django 4.1.2 on 2023-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_instructorcontactinfo_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
