# Generated by Django 4.1.2 on 2023-01-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_instructor_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructorcontactinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructorsocialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='instructorcontactinfo',
            name='contact_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='instructor.contactitem'),
        ),
        migrations.AddField(
            model_name='instructorsocialmedia',
            name='social_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='instructor.socialmediaitem'),
        ),
    ]
