# Generated by Django 4.1.2 on 2023-01-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_contactitem_socialmediaitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
