# Generated by Django 4.1.2 on 2023-02-01 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_alter_instructor_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
