# Generated by Django 4.1.2 on 2023-02-02 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_instructorrequest_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='handled_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
    ]
