# Generated by Django 4.1.2 on 2023-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_alter_instructorreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorreview',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
