# Generated by Django 4.1.2 on 2023-03-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0014_remove_instructorreview_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_handled', models.BooleanField(default=False)),
                ('instructor_message', models.TextField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('reviewer_decision', models.CharField(blank=True, choices=[('listing', 'listing'), ('unlisting', 'unlisting')], max_length=20, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('listing', 'listing'), ('unlisting', 'unlisting')], default='listing', max_length=20, verbose_name='Type of Request')),
                ('terms_accepted', models.BooleanField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
