# Generated by Django 4.1.2 on 2023-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_listingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='request_type',
            field=models.CharField(choices=[('listed', 'listed'), ('unlisted', 'unlisted')], default='listed', max_length=20, verbose_name='Type of Request'),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='reviewer_decision',
            field=models.CharField(blank=True, choices=[('listed', 'listed'), ('unlisted', 'unlisted')], max_length=20, null=True),
        ),
    ]
