# Generated by Django 4.1.2 on 2023-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_alter_listingrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='request_type',
            field=models.CharField(choices=[('list', 'list'), ('unlist', 'unlist')], default='list', max_length=20, verbose_name='Type of Request'),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='reviewer_decision',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('unlist', 'unlist')], max_length=20, null=True),
        ),
    ]
