# Generated by Django 4.1.2 on 2022-11-15 13:20

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0005_alter_instructorcontactinfo_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('paid', 'paid course'), ('free', 'free course'), ('private', 'private course')], default='free', max_length=20, verbose_name='Type of Course')),
                ('language', models.CharField(choices=[('arabic', 'arabic'), ('english', 'english'), ('mixed', 'mixed')], default='arabic', max_length=20, verbose_name='Language of Course')),
                ('description', models.CharField(max_length=3000, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('certified', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='courses/thumbnail')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('lectures', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('skills', models.IntegerField(default=0)),
                ('is_certificate', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(related_name='contributed_courses', to='instructor.instructor')),
                ('enrolled', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructor.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, default=10, null=True)),
                ('source', models.FileField(null=True, upload_to=course.models.upload_to)),
                ('key', models.CharField(max_length=300, null=True)),
                ('aws_bucket_name', models.CharField(default='allemniy-main', max_length=200, null=True)),
                ('aws_bucket_region', models.CharField(default='me-south-1', max_length=200, null=True)),
                ('formatted_vid_bucket', models.CharField(blank=True, max_length=200, null=True)),
                ('formatted_vid_key', models.CharField(blank=True, max_length=200, null=True)),
                ('formatted_vid_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.chapter')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='instructor.instructor')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('instructors', models.ManyToManyField(related_name='sections_teaching', to='instructor.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased', to='course.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='course.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.section'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='course.course'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='instructor.instructor'),
        ),
    ]
