# Generated by Django 4.1.2 on 2022-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='skills',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('all_levels', 'All levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='all_levels', max_length=20, verbose_name='Level of Course'),
        ),
    ]
