# Generated by Django 4.1.2 on 2022-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='short_description',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='is_certificate',
            new_name='certificate',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Alllevels', 'All levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='all_levels', max_length=20, verbose_name='Level of Course'),
        ),
    ]
