# Generated by Django 4.1.2 on 2022-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_short_description_course_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
