# Generated by Django 4.1.2 on 2022-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_section_course_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('arabic', 'arabic'), ('english', 'english'), ('mixed', 'mixed')], default='arabic', max_length=20, null=True, verbose_name='Language of Course'),
        ),
    ]
