# Generated by Django 4.1.2 on 2022-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_lecture_type_alter_lecture_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='source',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
