# Generated by Django 4.1.2 on 2022-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_lecture_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('premium', 'premium lecture'), ('free', 'free lecture')], default='premium', max_length=20, verbose_name='Type of Lecture'),
        ),
    ]
