# Generated by Django 4.1.2 on 2022-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_chapter_options_lecture_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
