# Generated by Django 4.1.2 on 2022-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='cloudfront_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
