# Generated by Django 4.1.2 on 2022-12-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_lecture_cloudfront_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='num_lectures',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='num_lectures',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
