# Generated by Django 4.1.2 on 2022-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_course_lectures_chapter_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='convert_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
