# Generated by Django 4.1.2 on 2022-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_lecture_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
