# Generated by Django 4.1.2 on 2022-12-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_instructorcontactinfo_instructor_and_more'),
        ('course', '0020_alter_lecture_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_handled', models.BooleanField(default=False)),
                ('instructor_message', models.TextField(blank=True, null=True)),
                ('reviwer_note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='publish', max_length=20, verbose_name='Type of Request')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
        ),
    ]
