# Generated by Django 4.1.2 on 2022-12-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_publicationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
