# Generated by Django 4.1.2 on 2022-12-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_publicationrequest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_requests', to='course.course'),
        ),
    ]
