# Generated by Django 4.1.2 on 2022-12-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0023_alter_publicationrequest_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationrequest',
            old_name='reviwer_note',
            new_name='reviewer_note',
        ),
        migrations.AddField(
            model_name='publicationrequest',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
