# Generated by Django 4.1.2 on 2022-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_rename_reviwer_note_publicationrequest_reviewer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='terms_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
