# Generated by Django 4.1.2 on 2023-01-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0005_alter_instructorcontactinfo_instructor_and_more'),
        ('course', '0026_course_num_reviews_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcourse',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soldcourse',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'manual'), ('paypal', 'paypal')], default='paypal', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_courses', to='instructor.instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='course.course'),
        ),
    ]
