# Generated by Django 4.1.2 on 2023-01-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='SoldCourse',
        ),
    ]
