# Generated by Django 4.1.2 on 2023-02-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_instructorrequest_requested_date'),
        ('course', '0030_alter_course_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='sections_teaching', to='instructor.instructor'),
        ),
    ]
