# Generated by Django 4.1.2 on 2023-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_section_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='reviewer_decision',
            field=models.CharField(blank=True, choices=[('publish', 'publish'), ('unpublish', 'unpublish')], max_length=20, null=True),
        ),
    ]
