# Generated by Django 4.1.2 on 2023-02-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_publicationrequest_reviewer_decision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationrequest',
            options={'ordering': ['-created_date']},
        ),
    ]
