# Generated by Django 4.1.2 on 2023-03-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_enrolledcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
    ]
