from django.urls import path

from .views import (
    SectionCourses, 
    SectionInstructors, 
    SectionList, 
    CourseList,
    UserCourse,
    CourseChapters,
    CourseEnroll,
    ChapterList,
    ChapterDetail,
    CourseDetail,
    CourseDashboard,
    UploadLecture,
    LectureDetail,
    FrontendUpload,
    RateCourse,
    CreateCourseFaq,
    CreateCourseBenefit,
    CoursePrice,
    CartItems,
    CoursePage,
    UserCourses,
    MarkCompletedLecture,
    PublicationRequests,
    HandlePublication
    )


urlpatterns = [
    path('', CourseList.as_view()),
    path('user-courses/', UserCourses.as_view()),
    path('publication-requests/', PublicationRequests.as_view()),
    path('handle-publication/<int:pk>/', HandlePublication.as_view()),
    path('<int:pk>/', CourseDetail.as_view()),
    path('course-dashborad/<int:pk>/', CourseDashboard.as_view()),
    path('course-price/<int:pk>/', CoursePrice.as_view()),
    path('delete-course/<int:pk>/', CourseDetail.as_view()),
    path('course-page/<int:pk>/', CoursePage.as_view()),
    path('sections/', SectionList.as_view()),
    path('create-benefit/', CreateCourseBenefit.as_view()),
    path('create-faq/', CreateCourseFaq.as_view()),
    path('create-chapter/', ChapterList.as_view()),
    path('update-chapter/<int:pk>/', ChapterDetail.as_view()),
    path('delete-chapter/<int:pk>/', ChapterDetail.as_view()),
    path('section-courses/<int:pk>/', SectionCourses.as_view()),
    path('section-instructors/<int:pk>/', SectionInstructors.as_view()),
    path('user-course/', UserCourse.as_view()),
    path('user-courses/delete/<int:pk>/', UserCourse.as_view()),
    path('enroll/<int:pk>/', CourseEnroll.as_view()),
    path('cart-items/<int:pk>/', CartItems.as_view()),
    path('upload-lecture/', UploadLecture.as_view()),
    path('update-lecture/<int:pk>/', LectureDetail.as_view()),
    path('delete-lecture/<int:pk>/', LectureDetail.as_view()),
    path('presigned-url/', FrontendUpload.as_view()),
    path('rate-course/<int:pk>/', RateCourse.as_view()),
    path('completed-lecture/<int:pk>/', MarkCompletedLecture.as_view()),
]