# Generated by Django 4.1.2 on 2023-02-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_generalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
    ]
